#!/usr/bin/env bash
# Build the wg0 policy-routing nft set used by entry points (m9-14 / m9-16):
#   * @force_m13 (Google + Meta/WhatsApp) -> ALWAYS mark 0x1 -> table 100 -> m9-13
#     (checked first, so it wins even over the ru/cn whitelist)
#   * @direct4   (ru/cn + local nets)     -> DIRECT local egress
#   * everything else                     -> mark 0x1 -> m9-13 (foreign exit)
set -euo pipefail
RU_URL="${RU_URL:-https://github.com/xyzmean/radb-tools/releases/download/latest/ru_cn_all.lst}"
FORCE_URL="${FORCE_URL:-https://github.com/xyzmean/m9-routes/releases/download/latest/force-m13.lst}"
OUT="${OUT:-/etc/nftables.d/wg-pbr.nft}"
# extra local /32s to keep DIRECT (this node's own public IPs, m9-13)
MYIP="$(ip route get 1.1.1.1 2>/dev/null | grep -oP "src \K[0-9.]+" | head -1)"
LOCAL_KEEP="${LOCAL_KEEP:-45.144.53.1/32${MYIP:+,$MYIP/32}}"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

curl -fsSL --retry 3 --connect-timeout 15 -o "$TMP/ru.lst"    "$RU_URL"    || { echo "ru list download failed" >&2; exit 1; }
curl -fsSL --retry 3 --connect-timeout 15 -o "$TMP/force.lst" "$FORCE_URL" || { echo "force list download failed" >&2; exit 1; }

RU="$(grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(/[0-9]+)?$' "$TMP/ru.lst" || true)"
FORCE="$(grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(/[0-9]+)?$' "$TMP/force.lst" || true)"
RU_CNT="$(printf '%s\n' "$RU" | grep -c . || true)"
FORCE_CNT="$(printf '%s\n' "$FORCE" | grep -c . || true)"
[ "${RU_CNT:-0}" -ge 1000 ]  || { echo "ru list too small ($RU_CNT), aborting" >&2; exit 1; }
[ "${FORCE_CNT:-0}" -ge 50 ] || { echo "force list too small ($FORCE_CNT), aborting" >&2; exit 1; }

RU_EL="$(printf '%s\n' "$RU" | sed 's/[[:space:]]//g; s/$/,/')"
FORCE_EL="$(printf '%s\n' "$FORCE" | sed 's/[[:space:]]//g; s/$/,/')"
KEEP_EL="$(printf '%s\n' "$LOCAL_KEEP" | tr ',' '\n' | sed 's/[[:space:]]//g; s/$/,/')"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<NFT
#!/usr/sbin/nft -f
# Auto-generated by m9-routes/update-routes.sh -- do not edit by hand.
table ip wgpbr
delete table ip wgpbr
table ip wgpbr {
    set force_m13 {
        type ipv4_addr
        flags interval
        auto-merge
        elements = {
$FORCE_EL
        }
    }
    set direct4 {
        type ipv4_addr
        flags interval
        auto-merge
        elements = {
            0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8,
            169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0/4,
$KEEP_EL
$RU_EL
        }
    }
    chain prerouting {
        type filter hook prerouting priority mangle; policy accept;
        iifname != "wg0" return
        ip daddr @force_m13 meta mark set 0x1 counter return
        ip daddr @direct4 counter return
        meta mark set 0x1 counter
    }
    chain postrouting {
        type filter hook postrouting priority mangle; policy accept;
        oifname "wg1" tcp flags syn tcp option maxseg size set rt mtu
    }
}
NFT

/usr/sbin/nft -f "$OUT"
echo "wg-pbr: loaded force_m13=$FORCE_CNT direct4=$RU_CNT (+local)"
